// GENERATED by @repogo/syntax-theme — DO NOT EDIT.
// Source: @jerrick/syntax-theme (mirrored at packages/syntax-theme/src/tokens.json)
// Regenerate: bun run gen:syntax-theme

import Foundation

/// Syntax-highlight palette for iOS markdown code blocks, shared with the web
/// + editor surfaces. Keyed by highlight.js scope (class name minus `hljs-`,
/// plus the bare `function_` / `class_` modifiers).
nonisolated enum SyntaxTheme {
  /// Default code text color (no scope) — light/dark.
  static let defaultForeground: (light: UInt32, dark: UInt32) = (0x383a42, 0x9cdcfe)

  /// Foreground color for a highlight.js scope, or nil to use defaultForeground.
  static func color(forScope scope: String, dark: Bool) -> UInt32? {
    switch scope {
    case "keyword": return dark ? 0x569cd6 : 0x0000ff
    case "doctag": return dark ? 0x569cd6 : 0x0000ff
    case "formula": return dark ? 0x569cd6 : 0x0000ff
    case "selector-tag": return dark ? 0x569cd6 : 0x0000ff
    case "type": return dark ? 0x4ec9b0 : 0x267f99
    case "built_in": return dark ? 0x4ec9b0 : 0x267f99
    case "name": return dark ? 0x4ec9b0 : 0x267f99
    case "selector-id": return dark ? 0x4ec9b0 : 0x267f99
    case "selector-class": return dark ? 0x4ec9b0 : 0x267f99
    case "selector-attr": return dark ? 0x4ec9b0 : 0x267f99
    case "selector-pseudo": return dark ? 0x4ec9b0 : 0x267f99
    case "class_": return dark ? 0x4ec9b0 : 0x267f99
    case "title": return dark ? 0xdcdcaa : 0x795e26
    case "function_": return dark ? 0xdcdcaa : 0x795e26
    case "section": return dark ? 0xdcdcaa : 0x795e26
    case "variable": return dark ? 0x9cdcfe : 0x0070c1
    case "template-variable": return dark ? 0x9cdcfe : 0x0070c1
    case "attr": return dark ? 0x9cdcfe : 0x0070c1
    case "attribute": return dark ? 0x9cdcfe : 0x0070c1
    case "property": return dark ? 0x9cdcfe : 0x0070c1
    case "symbol": return dark ? 0x9cdcfe : 0x0070c1
    case "bullet": return dark ? 0x9cdcfe : 0x0070c1
    case "params": return dark ? 0x9cdcfe : 0x0070c1
    case "subst": return dark ? 0x9cdcfe : 0x0070c1
    case "number": return dark ? 0xb5cea8 : 0x098658
    case "literal": return dark ? 0xb5cea8 : 0x098658
    case "string": return dark ? 0xce9178 : 0xa31515
    case "addition": return dark ? 0xce9178 : 0xa31515
    case "char": return dark ? 0xce9178 : 0xa31515
    case "regexp": return dark ? 0xd16969 : 0xaf00db
    case "comment": return dark ? 0x6a9955 : 0x008000
    case "quote": return dark ? 0x6a9955 : 0x008000
    case "meta": return dark ? 0x6a9955 : 0x008000
    case "operator": return dark ? 0xd4d4d4 : 0x383a42
    case "punctuation": return dark ? 0xd4d4d4 : 0x383a42
    case "deletion": return dark ? 0xff0000 : 0xe45649
    case "link": return dark ? 0x6a9955 : 0x4078f2
    default: return nil
    }
  }
}
